languages:
  Ruby: true
  JavaScript: false
exclude_paths:
- "app/controllers/concerns/*_doc.rb"
- "public/api"
- "lib/tasks"
- "public/coverage"
- "test"
- "public/javascripts"
- "lib/sample_data.rb"
- "app/controllers/*.rb"
- "!app/controllers/application_controller.rb"
- "db/migrate"
- "app/graphql"
- "doc"
