languages:
  Ruby: true
  JavaScript: false
engines:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  duplication:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- "app/controllers/concerns/*_doc.rb"
- "public/api"
- "lib/tasks"
- "public/coverage"
- "test"
- "public/javascripts"
- "lib/sample_data.rb"
- "app/controllers/*.rb"
- "!app/controllers/application_controller.rb"
- "db/migrate"
- "app/graphql"
- "doc"
- "app/models/ability.rb"
- ".codeclimate.yml"
